### ISSUE TITLE
Package `compiler` is not a member of the workspace

### ISSUE THREAD

**Issue by Sirius902** [CryZe/WindWakerDebugMenu#8]
I'm trying to compile the debug menu with `rustc 1.38.0-nightly (00ee1b47f 2019-08-11)` and I'm getting the error ```error: package `compiler` is not a member of the workspace``` when attempting to execute `cargo run -p compiler --release` as instructed by the readme.

**Comment by hallcristobal** [comment]
The README on this repository is actually out of date, please follow the readme here: 
https://github.com/hallcristobal/TwilightPrincessDebugMenu/blob/master/README.md
until we have it updated. Sorry for the confusion.

**Comment by Sirius902** [comment]
Ah alright. Thank you, I managed to compile it now.
